// Nigerian Universities Data
const NIGERIAN_UNIVERSITIES = [
  // Federal Universities
  "University of Abuja",
  "Ahmadu Bello University, Zaria",
  "Bayero University Kano",
  "Federal University of Agriculture, Abeokuta",
  "Federal University of Agriculture, Makurdi",
  "Federal University of Petroleum Resources, Effurun",
  "Federal University of Technology, Akure",
  "Federal University of Technology, Minna",
  "Federal University of Technology, Owerri",
  "Federal University, Dutsin-Ma",
  "Federal University, Gashua",
  "Federal University, Gusau",
  "Federal University, Kashere",
  "Federal University, Lafia",
  "Federal University, Lokoja",
  "Federal University, Otuoke",
  "Federal University, Oye-Ekiti",
  "Federal University, Wukari",
  "Federal University, Birnin Kebbi",
  "Federal University, Ikot Akpan",
  "Federal University, Ndifu-Alike",
  "Modibbo Adama University of Technology, Yola",
  "National Open University of Nigeria",
  "University of Calabar",
  "University of Ibadan",
  "University of Ilorin",
  "University of Lagos",
  "University of Maiduguri",
  "University of Nigeria, Nsukka",
  "University of Port Harcourt",
  "University of Uyo",
  "Usmanu Danfodiyo University, Sokoto",
  "University of Benin",
  "Nnamdi Azikiwe University, Awka",
  
  // State Universities
  "Abia State University, Uturu",
  "Adamawa State University, Mubi",
  "Akwa Ibom State University, Obio Akpa",
  "Ambrose Alli University, Ekpoma",
  "Bauchi State University, Gadau",
  "Benue State University, Makurdi",
  "Cross River State University of Technology, Calabar",
  "Delta State University, Abraka",
  "Ebonyi State University, Abakaliki",
  "Ekiti State University, Ado-Ekiti",
  "Enugu State University of Science and Technology, Enugu",
  "Gombe State University, Gombe",
  "Imo State University, Owerri",
  "Jigawa State University, Dutse",
  "Kaduna State University, Kaduna",
  "Kano State University of Science and Technology, Kano",
  "Katsina State University, Katsina",
  "Kebbi State University of Science and Technology, Aliero",
  "Kogi State University, Anyigba",
  "Kwara State University, Malete",
  "Lagos State University, Lagos",
  "Nasarawa State University, Keffi",
  "Niger State University of Science and Technology, Zaria",
  "Ogun State University, Ago-Iwoye",
  "Ondo State University of Science and Technology, Okitipupa",
  "Osun State University, Osogbo",
  "Oyo State University, Saki",
  "Plateau State University, Bokkos",
  "Rivers State University, Port Harcourt",
  "Sokoto State University, Sokoto",
  "Taraba State University, Jalingo",
  "Yobe State University, Damaturu",
  "Zamfara State University, Gusau",
  "Lagos State University of Science and Technology",
  "Ondo State University of Technology, Akure",
  
  // Private Universities
  "Achievers University, Owo",
  "Ajayi Crowther University, Ibadan",
  "Akhigbe University, Ikeja",
  "American University of Nigeria, Yola",
  "Anchor University, Lagos",
  "Augustine University, Lagos",
  "Babcock University, Ilishan-Remo",
  "Baze University, Abuja",
  "Bells University of Technology, Ota",
  "Benson Idahosa University, Benin City",
  "Bowen University, Iwo",
  "Calabar University, Calabar",
  "Carlito University, Port Harcourt",
  "Covenant University, Canaan Land",
  "Crawford University, Igbesa",
  "David Umahi Federal University of Health Sciences, Uburu",
  "Dominican University, Ibadan",
  "Eko University of Medicine and Health Sciences, Lagos",
  "Elizade University, Ilara-Mokin",
  "Fountain University, Osun State",
  "Hallmark University, Ijebu-Itele",
  "Houdegbe North American University, Cotonou",
  "Ifeoluwa University, Osun State",
  "Joseph Ayo Babalola University, Ikeji",
  "Kingdom University, Madalla",
  "Koladaisi University, Ibadan",
  "Kwasu Kogi State University",
  "Lead City University, Ibadan",
  "Lecicon University, Ijebu-Ode",
  "Logos University, Badagry",
  "Madonna University, Okija",
  "Mcpherson University, Sereki",
  "Mediatech University, Anambra State",
  "Merit University, Ogun State",
  "Michael Okpara University of Agriculture, Umudike",
  "Milestone University, Lagos",
  "Mountain Top University, Ogun State",
  "Nile University of Nigeria, Abuja",
  "Novena University, Ogume",
  "Oduduwa University, Osun State",
  "Ogun State Institute of Technology, Abeokuta",
  "Osun State College of Technology, Esa-Oke",
  "Pan-Atlantic University, Lagos",
  "Redeemers University, Ede",
  "Regent University, Lagos",
  "Ritman University, Ikot Ekpene",
  "Sule Lamido University, Kafin Hausa",
  "Sustainable University, Anambra State",
  "Tansian University, Umunya",
  "Topfaith University, Enugu",
  "Trinity University, Ota",
  "University of Ilorin (Private Programme)",
  "University of Jos (Distance Learning)",
  "University of the Gambia (if applicable)",
  "UNIABUJA (Distance Learning)",
  "Veritas University, Abuja",
  "Victoria University, Bauchi",
  "Wesley University of Science and Technology, Ondo State",
  "Western Delta University, Delta State",
  "Westfield University, Kogi State",
  "Wellspring University, Benin City",
  "Wigwie University",
  "Xaverian University, Owerri",
  "Yusuf Maitama Sule University, Kano",
  "Zenith Medical and Technology University, Osun State"
];

// Function to search universities
function searchUniversities(query) {
  if (!query) return NIGERIAN_UNIVERSITIES;
  return NIGERIAN_UNIVERSITIES.filter(uni =>
    uni.toLowerCase().includes(query.toLowerCase())
  );
}
